export type Fragment={id:string;title:string;kind:string;year:number;date:string;place:string;people:string[];event:string;text:string;image?:string;media?:string;mime?:string;source:string};
export type Question={id:string;text:string;person:string;fragment:string;why:string};
export const people=[{id:'meera',name:'Meera',relationship:'Aunt · The storyteller',quote:'It wasn’t a grand house. But everyone always found a place at our table.'},{id:'anil',name:'Anil',relationship:'Father · A keeper of letters',quote:'The mango tree was the first thing I noticed.'},{id:'kavita',name:'Kavita',relationship:'Mother · The family cook',quote:'A recipe is only the beginning. You have to taste as you go.'},{id:'raj',name:'Raj',relationship:'Uncle · Always on a journey',quote:'We watched the cities change outside the window.'},{id:'asha',name:'Asha',relationship:'Grandmother · Our steady centre',quote:'Come in. There is always enough for one more.'},{id:'riya',name:'Riya',relationship:'Daughter · Collecting the little things',quote:'I want to remember the ordinary afternoons, too.'}];
export const events=[{id:'wedding',title:'The wedding afternoon',year:1987},{id:'house',title:'The house with the mango tree',year:1994},{id:'kitchen',title:'Sunday in the kitchen',year:2002},{id:'train',title:'The first train journey',year:1976},{id:'afternoon',title:'An ordinary afternoon',year:2011}];
const f=(id:string,title:string,kind:string,year:number,date:string,place:string,persons:string[],event:string,text:string,image?:string):Fragment=>({id,title,kind,year,date,place,people:persons,event,text,image,source:'Fictional Mehra family demo · '+(image?'AI-generated illustrative photograph':'Authored sample record')});
export const initialFragments:Fragment[]=[
f('wedding-photo','The wedding afternoon','Photographs',1987,'December 1987','Delhi',['meera','anil','asha'],'wedding','Everyone gathered in the courtyard before lunch. Someone beside the blue doorway is still waiting to be named.','/images/wedding.png'),
f('house-photo','The house with the mango tree','Photographs',1994,'July 1994','Pune',['anil','kavita','meera'],'house','Our new home, with room for a table beneath the mango tree.','/images/house.png'),
f('meera-portrait','Meera, the storyteller','Photographs',2011,'Around 2011','Pune',['meera'],'afternoon','She remembers the songs, the names, and who went back for seconds.','/images/meera.png'),
f('letter','A letter from our new home','Letters',1994,'18 July 1994','Pune',['anil','meera'],'house','My dear Meera,\nThe house is smaller than we imagined. But there is a mango tree in the courtyard, and already it feels like ours. Come soon. There is so much to tell.\nWith love, Anil'),
f('recipe','Kavita’s mango pickle','Letters',2002,'Summer 2002','Pune',['kavita','asha'],'kitchen','Green mangoes, mustard seeds, turmeric, chilli and salt. Dry the mango pieces in the afternoon sun. Warm the oil, then let it cool. Mix gently. Wait three days. Taste together.'),
f('ticket','Two seats, one beginning','Letters',1976,'16 June 1976','Delhi → Bombay',['raj','anil'],'train','INDIAN RAILWAYS\nDelhi → Bombay\nSecond class · Two passengers\nTicket № 047219\nA journey remembered in fragments.'),
f('kitchen-voice','“Taste as you go.”','Voices',2002,'Around 2002','Pune',['kavita'],'kitchen','The measurements were never exact. A little more salt, a little less chilli. Mother would say: a recipe is only the beginning. You have to taste as you go.'),
f('wedding-voice','“We danced until the lights went out.”','Voices',1987,'Recollection recorded 2011','Delhi',['meera'],'wedding','I remember the marigolds in the courtyard, and everyone laughing when the power went out. We kept singing anyway.'),
f('moving-message','Have you reached safely?','Messages',1994,'July 1994','Delhi',['asha','anil'],'house','Have you reached safely? Put the kettle on before you unpack. A house begins to feel like home with the first cup of tea.'),
f('train-note','The window seat','Letters',1976,'Around 1976','On the train',['raj'],'train','I remember an orange seller at a station. I can’t remember which station, but Anil bought enough for the whole compartment.'),
f('afternoon-note','An ordinary afternoon','Messages',2011,'October 2011','Pune',['riya','meera','asha'],'afternoon','No birthday. No occasion. Just tea, a game of cards, and the sound of everyone talking at once.'),
f('wedding-menu','Lunch in the courtyard','Letters',1987,'December 1987','Delhi',['kavita','asha'],'wedding','For the family: dal makhani, jeera rice, warm rotis, aloo gobi, and a little extra kheer. Keep a plate for whoever arrives late.'),
f('mango-memory','The first mango season','Voices',1995,'Recollection of summer 1995','Pune',['anil','riya'],'house','The first year, there were only seven mangoes. We counted them every morning. When they finally ripened, we shared them with the neighbours.'),
f('recipe-message','Don’t forget the mustard seeds','Messages',2002,'Summer 2002','Pune',['asha','kavita'],'kitchen','Toast them gently, just until they begin to dance. And never put a wet spoon into the pickle jar.'),
f('train-letter','A postcard home','Letters',1976,'June 1976','Bombay',['anil','asha'],'train','We arrived this morning. Raj still insists his window seat was the better one. The city is louder than I imagined. We are well.'),
f('afternoon-voice','A place at our table','Voices',2011,'October 2011','Pune',['meera','riya'],'afternoon','It wasn’t a grand house. But everyone always found a place at our table.')];
export const questions:Question[]=[{id:'demo-question',text:'Who was standing beside the blue doorway in this photograph?',person:'meera',fragment:'wedding-photo',why:'She appears in this photograph and contributed another memory from the same wedding.'},{id:'mango-question',text:'Who planted the mango tree before you moved in?',person:'anil',fragment:'house-photo',why:'Anil wrote the first letter from the house and remembers the first mango season.'},{id:'train-question',text:'At which station did you buy oranges for everyone?',person:'raj',fragment:'ticket',why:'Raj mentioned the orange seller in his note about the window seat.'}];
export type Chapter={id:string;title:string;fragment:string;included:boolean};
export const initialChapters:Chapter[]=[{id:'c1',title:'A new beginning',fragment:'house-photo',included:true},{id:'c2',title:'A letter home',fragment:'letter',included:true},{id:'c3',title:'Everyone at the table',fragment:'meera-portrait',included:true},{id:'c4',title:'Every voice adds something only it can.',fragment:'wedding-photo',included:true}];
export type State={fragments:Fragment[];statuses:Record<string,string>;chapters:Chapter[]};
export const seed:State={fragments:initialFragments,statuses:{},chapters:initialChapters};
const key='mnemovault-v1';
export function readState():State{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):seed}catch{return seed}}
export function writeState(s:State){localStorage.setItem(key,JSON.stringify(s))}
export function db():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const req=indexedDB.open('mnemovault-media',1);req.onupgradeneeded=()=>req.result.createObjectStore('files');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
export async function saveBlob(id:string,blob:Blob){const d=await db();return new Promise<void>((resolve,reject)=>{const t=d.transaction('files','readwrite');t.objectStore('files').put(blob,id);t.oncomplete=()=>{d.close();resolve()};t.onerror=()=>{d.close();reject(t.error)}})}
export async function getBlob(id:string){const d=await db();return new Promise<Blob|undefined>((resolve,reject)=>{const r=d.transaction('files').objectStore('files').get(id);r.onsuccess=()=>{d.close();resolve(r.result)};r.onerror=()=>{d.close();reject(r.error)}})}
export async function clearMedia(){const d=await db();return new Promise<void>((resolve,reject)=>{const t=d.transaction('files','readwrite');t.objectStore('files').clear();t.oncomplete=()=>{d.close();resolve()};t.onerror=()=>reject(t.error)})}
